In [1]:
import numpy as np

In [2]:
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [5]:
print ridership[1, 3]
print ridership[1:3, 3:5]
print ridership[1, :]
print ridership[2:5, 2:5]

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]
[[3991 6461 2691]
 [3826 4787 2613]
 [3932 4477 2705]]


In [11]:
print ridership[0, :] + ridership[1, :]
print ridership[:, 0] + ridership[:, 1]

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print a + b

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [16]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    '''
    
    # find the station with the max rider for first day
    max_station = ridership[0, :].argmax()
    
    # find the mean rider per day for that station
    mean_for_max = ridership[:, max_station].mean()
    
    # find the mean ridership overall for comparison
    overall_mean = ridership.mean()
    
    return (overall_mean, mean_for_max)

print mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)


In [17]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. 
    '''
    station_riders = ridership.mean(axis=0)
    max_daily_ridership = station_riders.max() 
    min_daily_ridership = station_riders.min()
    
    return (max_daily_ridership, min_daily_ridership)
    
print min_and_max_riders_per_day(ridership)

(3239.9000000000001, 1071.2)


In [28]:
# %load test.py
import numpy as np
import pandas as pd

enrollments_df = pd.DataFrame({
    'account_key': [448, 448, 448, 448, 448],
    'status': ['canceled', 'canceled', 'canceled', 'canceled', 'canceled'],
    'join_date': ['2014-11-10', '2014-11-05',  '2015-01-27', '2014-1-10', '2015-03-10'],
    'days_to_cancel': [65, 5, 0, 0, np.nan],
    'is_udacity': [True, True, True, True, True]
    })

enrollments_df

account_key  days_to_cancel is_udacity   join_date    status
0          448            65.0       True  2014-11-10  canceled
1          448             5.0       True  2014-11-05  canceled
2          448             0.0       True  2015-01-27  canceled
3          448             0.0       True   2014-1-10  canceled
4          448             NaN       True  2015-03-10  canceled

In [29]:
enrollments_df.mean()

account_key       448.0
days_to_cancel     17.5
is_udacity          1.0
dtype: float64