In [1]:
import numpy as np

In [2]:
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [5]:
print ridership[1, 3]
print ridership[1:3, 3:5]
print ridership[1, :]
print ridership[2:5, 2:5]

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]
[[3991 6461 2691]
 [3826 4787 2613]
 [3932 4477 2705]]


In [11]:
print ridership[0, :] + ridership[1, :]
print ridership[:, 0] + ridership[:, 1]

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print a + b

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [16]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    '''
    
    # find the station with the max rider for first day
    max_station = ridership[0, :].argmax()
    
    # find the mean rider per day for that station
    mean_for_max = ridership[:, max_station].mean()
    
    # find the mean ridership overall for comparison
    overall_mean = ridership.mean()
    
    return (overall_mean, mean_for_max)

print mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)


In [17]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. 
    '''
    station_riders = ridership.mean(axis=0)
    max_daily_ridership = station_riders.max() 
    min_daily_ridership = station_riders.min()
    
    return (max_daily_ridership, min_daily_ridership)
    
print min_and_max_riders_per_day(ridership)

(3239.9000000000001, 1071.2)


In [28]:
# %load test.py
import numpy as np
import pandas as pd

enrollments_df = pd.DataFrame({
    'account_key': [448, 448, 448, 448, 448],
    'status': ['canceled', 'canceled', 'canceled', 'canceled', 'canceled'],
    'join_date': ['2014-11-10', '2014-11-05',  '2015-01-27', '2014-1-10', '2015-03-10'],
    'days_to_cancel': [65, 5, 0, 0, np.nan],
    'is_udacity': [True, True, True, True, True]
    })

enrollments_df

account_key  days_to_cancel is_udacity   join_date    status
0          448            65.0       True  2014-11-10  canceled
1          448             5.0       True  2014-11-05  canceled
2          448             0.0       True  2015-01-27  canceled
3          448             0.0       True   2014-1-10  canceled
4          448             NaN       True  2015-03-10  canceled

In [29]:
enrollments_df.mean()

account_key       448.0
days_to_cancel     17.5
is_udacity          1.0
dtype: float64

In [31]:
# You can create a DataFrame out of a dictionary mapping column names to values
df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print df_1

print "\n===============================\n"

# You can also use a list of lists or a 2D NumPy array
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
print df_2

   A  B
0  0  3
1  1  4
2  2  5


   A  B  C
0  0  1  2
1  3  4  5


In [38]:
# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [47]:
# use iloc to access rows by position
print ridership_df.iloc[0]

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64


In [48]:
# use loc to access rows by index
print ridership_df.loc['05-05-11']

R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64


In [54]:
print ridership_df.iloc[0, 3]

5


In [52]:
print ridership_df.loc['05-05-11', 'R005']

3932


In [65]:
print ridership_df.iloc[1:4]

          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613


In [57]:
# Access coloumn by square bracket
print ridership_df['R003']

05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64


In [66]:
print ridership_df[['R003', 'R005']]

          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [60]:
ridership_df.values

array([[   0,    0,    2,    5,    0],
       [1478, 3877, 3674, 2328, 2539],
       [1613, 4088, 3991, 6461, 2691],
       [1560, 3392, 3826, 4787, 2613],
       [1608, 4802, 3932, 4477, 2705],
       [1576, 3933, 3909, 4979, 2685],
       [  95,  229,  255,  496,  201],
       [   2,    0,    1,   27,    0],
       [1438, 3785, 3589, 4174, 2215],
       [1342, 4043, 4009, 4665, 3033]])

In [61]:
print ridership_df.values.mean()

2342.6


In [62]:
print ridership_df.mean()

R003    1071.2
R004    2814.9
R005    2718.8
R006    3239.9
R007    1868.2
dtype: float64


In [70]:
df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print df
print "\n=================\n"

print df.sum(axis=0)
print "\n=================\n"

print df.sum(axis=1)
print "\n=================\n"

# by default axis is supposed to be zero
print df.sum()
print "\n=================\n"

print df.values.sum()

   A  B
0  0  3
1  1  4
2  2  5


A     3
B    12
dtype: int64


0    3
1    5
2    7
dtype: int64


A     3
B    12
dtype: int64


15


In [79]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    
 
    # find the station with the max riders on first day
    max_station = ridership.iloc[0].argmax()
    
    # find the mean riders per day for that station
    mean_for_max = ridership[max_station].mean()
    
    # find the mean ridership overall for comparison
    overall_mean = ridership.values.mean()
    
    return (overall_mean, mean_for_max)
    
print mean_riders_for_max_station(ridership_df)

(2342.5999999999999, 3239.9000000000001)


In [80]:
subway_df = pd.read_csv('../ch3_data/nyc_subway_weather.csv')

In [81]:
subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0            0.0  2011-05-01 00:00:00     0         6     ...           30.22   
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5         0.0         30.258      55.98       7.86   
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [82]:
subway_df.describe()

ENTRIESn        EXITSn  ENTRIESn_hourly  EXITSn_hourly  \
count  4.264900e+04  4.264900e+04     42649.000000   42649.000000   
mean   2.812486e+07  1.986993e+07      1886.589955    1361.487866   
std    3.043607e+07  2.028986e+07      2952.385585    2183.845409   
min    0.000000e+00  0.000000e+00         0.000000       0.000000   
25%    1.039762e+07  7.613712e+06       274.000000     237.000000   
50%    1.818389e+07  1.331609e+07       905.000000     664.000000   
75%    3.263049e+07  2.393771e+07      2255.000000    1537.000000   
max    2.357746e+08  1.493782e+08     32814.000000   34828.000000   

               hour      day_week       weekday      latitude     longitude  \
count  42649.000000  42649.000000  42649.000000  42649.000000  42649.000000   
mean      10.046754      2.905719      0.714436     40.724647    -73.940364   
std        6.938928      2.079231      0.451688      0.071650      0.059713   
min        0.000000      0.000000      0.000000     40.576152    -74.073622   
25%        4.000000      1.000000      0.000000     40.677107    -73.987342   
50%       12.000000      3.000000      1.000000     40.717241    -73.953459   
75%       16.000000      5.000000      1.000000     40.759123    -73.907733   
max       20.000000      6.000000      1.000000     40.889185    -73.755383   

                fog      ...          pressurei          rain         tempi  \
count  42649.000000      ...       42649.000000  42649.000000  42649.000000   
mean       0.009824      ...          29.971096      0.224741     63.103780   
std        0.098631      ...           0.137942      0.417417      8.455597   
min        0.000000      ...          29.550000      0.000000     46.900000   
25%        0.000000      ...          29.890000      0.000000     57.000000   
50%        0.000000      ...          29.960000      0.000000     61.000000   
75%        0.000000      ...          30.060000      0.000000     69.100000   
max        1.000000      ...          30.320000      1.000000     86.000000   

              wspdi   meanprecipi  meanpressurei     meantempi     meanwspdi  \
count  42649.000000  42649.000000   42649.000000  42649.000000  42649.000000   
mean       6.927872      0.004618      29.971096     63.103780      6.927872   
std        4.510178      0.016344       0.131158      6.939011      3.179832   
min        0.000000      0.000000      29.590000     49.400000      0.000000   
25%        4.600000      0.000000      29.913333     58.283333      4.816667   
50%        6.900000      0.000000      29.958000     60.950000      6.166667   
75%        9.200000      0.000000      30.060000     67.466667      8.850000   
max       23.000000      0.157500      30.293333     79.800000     17.083333   

        weather_lat   weather_lon  
count  42649.000000  42649.000000  
mean      40.728555    -73.938693  
std        0.065420      0.059582  
min       40.600204    -74.014870  
25%       40.688591    -73.985130  
50%       40.720570    -73.949150  
75%       40.755226    -73.912033  
max       40.862064    -73.694176  

[8 rows x 21 columns]

In [84]:
filename = '../ch3_data/nyc_subway_weather.csv'
subway_df = pd.read_csv(filename)

def correlation(x, y):
    '''
    Fill in this function to compute the correlation between the two
    input variables. Each input is either a NumPy array or a Pandas
    Series.
    
    correlation = average of (x in standard units) times (y in standard units)
    
    Remember to pass the argument "ddof=0" to the Pandas std() function!
    '''
    std_x = (x - x.mean()) / x.std(ddof=0)
    std_y = (y - y.mean()) / y.std(ddof=0)
    return (std_x * std_y).mean()

entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

print correlation(entries, rain)
print correlation(entries, temp)
print correlation(rain, temp)

print correlation(entries, cum_entries)

0.0356485157722
-0.0266933483216
-0.229034323408
0.585895470766


In [87]:
# Adding DataFrames with the column names
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]})
print df1
print "\n======================================\n"
print df2
print "\n======================================\n"
print df1 + df2

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9


    a   b   c
0  10  40  70
1  20  50  80
2  30  60  90


    a   b   c
0  11  44  77
1  22  55  88
2  33  66  99


In [88]:
# Adding DataFrames with overlapping column names
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'d': [10, 20, 30], 'c': [40, 50, 60], 'b': [70, 80, 90]})
print df1
print "\n=========================================\n"
print df2
print "\n=========================================\n"
print df1 + df2


   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9


    b   c   d
0  70  40  10
1  80  50  20
2  90  60  30


    a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN


In [89]:
# Adding DataFrames with overlapping row indexes
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                   index=['row1', 'row2', 'row3'])
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                   index=['row4', 'row3', 'row2'])
print df1
print "\n=========================================\n"
print df2
print "\n=========================================\n"
print df1 + df

      a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9


       a   b   c
row4  10  40  70
row3  20  50  80
row2  30  60  90


       A   B   a   b   c
0    NaN NaN NaN NaN NaN
1    NaN NaN NaN NaN NaN
2    NaN NaN NaN NaN NaN
row1 NaN NaN NaN NaN NaN
row2 NaN NaN NaN NaN NaN
row3 NaN NaN NaN NaN NaN


In [102]:
# Cumulative entries and exits for one station for a few hours.
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})

def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
    '''
    return entries_and_exits - entries_and_exits.shift(1)

In [103]:
get_hourly_entries_and_exits(entries_and_exits)

ENTRIESn  EXITSn
0       NaN     NaN
1      23.0     8.0
2      18.0    18.0
3      71.0    54.0
4     170.0    44.0
5     214.0    42.0
6      87.0    11.0
7      10.0     3.0
8      36.0    89.0
9     153.0   333.0

In [104]:
# DataFrame applymap()
df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [10, 20, 30],
    'c': [5, 10, 15]
})

def add_one(x):
    return x + 1

print df.applymap(add_one)

   a   b   c
0  2  11   6
1  3  21  11
2  4  31  16


In [105]:
def convert_grade(grade):
    if grade >= 90:
        return 'A'
    elif grade >= 80:
        return 'B'
    elif grade >= 70:
        return 'C'
    elif grade >= 60:
        return 'D'
    else:
        return 'F'

print convert_grade(80)

B


In [106]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)
    
def convert_grades(grades):
    '''
    Fill in this function to convert the given DataFrame of numerical
    grades to letter grades. Return a new DataFrame with the converted
    grade.
    
    The conversion rule is:
        90-100 -> A
        80-89  -> B
        70-79  -> C
        60-69  -> D
        0-59   -> F
    '''
    return grades.applymap(convert_grade)

In [109]:
convert_grades(grades_df)

exam1 exam2
Andre       F     F
Barry       B     D
Chris       C     F
Dan         C     F
Emilio      B     D
Fred        C     F
Greta       A     C
Humbert     D     F
Ivan        A     C
James       B     D

In [111]:
def convert_grades_curve(exam_grades):
    # Pandas has a bult-in function that will perform this calculation
    # This will give the bottom 0% to 10% of students the grade 'F',
    # 10% to 20% the grade 'D', and so on. You can read more about
    # the qcut() function here:
    # http://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html
    return pd.qcut(exam_grades,
                   [0, 0.1, 0.2, 0.5, 0.8, 1],
                   labels=['F', 'D', 'C', 'B', 'A'])

# qcut() operates on a list, array, or Series. This is the
# result of running the function on a single column of the
# DataFrame.
print convert_grades_curve(grades_df['exam1'])

# qcut() does not work on DataFrames, but we can use apply()
# to call the function on each column separately
print grades_df.apply(convert_grades_curve)

Andre      F
Barry      B
Chris      C
Dan        C
Emilio     B
Fred       C
Greta      A
Humbert    D
Ivan       A
James      B
Name: exam1, dtype: category
Categories (5, object): [F < D < C < B < A]
        exam1 exam2
Andre       F     F
Barry       B     B
Chris       C     C
Dan         C     C
Emilio      B     B
Fred        C     C
Greta       A     A
Humbert     D     D
Ivan        A     A
James       B     B


In [112]:
def standardize_column(column):
    return (column - column.mean()) / column.std()

standardize_column(grades_df['exam1'])

Andre     -2.196525
Barry      0.208891
Chris      0.018990
Dan       -0.170911
Emilio     0.715295
Fred      -0.487413
Greta      0.841896
Humbert   -0.803916
Ivan       1.284999
James      0.588694
Name: exam1, dtype: float64

In [113]:
def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    '''
    return df.apply(standardize_column)

standardize(grades_df)

exam1     exam2
Andre   -2.196525 -2.186335
Barry    0.208891  0.366571
Chris    0.018990 -0.091643
Dan     -0.170911 -0.091643
Emilio   0.715295  0.628408
Fred    -0.487413 -0.418938
Greta    0.841896  1.413917
Humbert -0.803916 -0.746234
Ivan     1.284999  0.955703
James    0.588694  0.170194

In [114]:
df = pd.DataFrame({
    'a': [4, 5, 3, 1, 2],
    'b': [20, 10, 40, 50, 30],
    'c': [25, 20, 5, 15, 10]
})

print df.apply(np.mean)

print df.apply(np.max)

a     3.0
b    30.0
c    15.0
dtype: float64
a     5
b    50
c    25
dtype: int64


In [120]:
def second_largest_in_column(column):
    sorted_column = column.sort_values(ascending=False)
    return sorted_column.iloc[1]

def second_largest(df):
    '''
    Fill in this function to return the second-largest value of each 
    column of the input DataFrame.
    '''
    return df.apply(second_largest_in_column)

In [121]:
second_largest_in_column(df['a'])

4

In [122]:
second_largest(df)

a     4
b    40
c    20
dtype: int64

In [123]:
# Adding a Series to a square DataFrame
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

print df
print '' # Create a blank line between outputs
print df + s

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [124]:
# Adding a Series to a one-row DataFrame
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10], 1: [20], 2: [30], 3: [40]})

print df
print '' # Create a blank line between outputs
print df + s

    0   1   2   3
0  10  20  30  40

    0   1   2   3
0  11  22  33  44


In [128]:
# Adding a Series to a one-column DataFrame

s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10, 20, 30, 40]})

print df
print '' # Create a blank line between outputs
print df + s
print ''
print df.add(s, axis='index')

    0
0  10
1  20
2  30
3  40

    0   1   2   3
0  11 NaN NaN NaN
1  21 NaN NaN NaN
2  31 NaN NaN NaN
3  41 NaN NaN NaN

    0
0  11
1  22
2  33
3  44


In [126]:
# Adding when DataFrame column names match Series index

s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
df = pd.DataFrame({
    'a': [10, 20, 30, 40],
    'b': [50, 60, 70, 80],
    'c': [90, 100, 110, 120],
    'd': [130, 140, 150, 160]
})

print df
print '' # Create a blank line between outputs
print df + s

    a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    a   b    c    d
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [127]:
# Adding when DataFrame column names don't match Series index

s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    'a': [10, 20, 30, 40],
    'b': [50, 60, 70, 80],
    'c': [90, 100, 110, 120],
    'd': [130, 140, 150, 160]
})

print df
print '' # Create a blank line between outputs
print df + s

    a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1   2   3   a   b   c   d
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN


In [129]:
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
df = pd.DataFrame({
    'b': [10, 20, 30, 40],
    'c': [50, 60, 70, 80],
    'd': [90, 100, 110, 120],
    'e': [130, 140, 150, 160]
})

print df
print '' # Create a blank line between outputs
print df + s

    b   c    d    e
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    a     b     c      d   e
0 NaN  12.0  53.0   94.0 NaN
1 NaN  22.0  63.0  104.0 NaN
2 NaN  32.0  73.0  114.0 NaN
3 NaN  42.0  83.0  124.0 NaN


In [130]:
# Adding using +
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

print df
print '' # Create a blank line between outputs
print df + s

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [131]:
# Adding with axis='index'

s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

print df
print '' # Create a blank line between outputs
print df.add(s, axis='index')
 # The functions sub(), mul(), and div() work similarly to add()

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  51   91  131
1  22  62  102  142
2  33  73  113  153
3  44  84  124  164


In [132]:
# Adding with axis='columns'
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

print df
print '' # Create a blank line between outputs
print df.add(s, axis='columns')
    # The functions sub(), mul(), and div() work similarly to add()

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [137]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89],
          'exam2': [24, 63, 56, 56, 67]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio']
)

grades_df

exam1  exam2
Andre      43     24
Barry      81     63
Chris      78     56
Dan        75     56
Emilio     89     67

In [138]:
grades_df.mean()

exam1    73.2
exam2    53.2
dtype: float64

In [141]:
# standardize each column
(grades_df - grades_df.mean()) / grades_df.std()

exam1     exam2
Andre  -1.709191 -1.718539
Barry   0.441447  0.576770
Chris   0.271659  0.164791
Dan     0.101872  0.164791
Emilio  0.894212  0.812186

In [143]:
grades_df.mean(axis='columns')

Andre     33.5
Barry     72.0
Chris     67.0
Dan       65.5
Emilio    78.0
dtype: float64

In [145]:
# standardize each row
mean_diffs = grades_df.sub(grades_df.mean(axis='columns'), axis='index')
mean_diffs

exam1  exam2
Andre     9.5   -9.5
Barry     9.0   -9.0
Chris    11.0  -11.0
Dan       9.5   -9.5
Emilio   11.0  -11.0

In [146]:
mean_diffs.div(grades_df.std(axis='columns'), axis='index')

exam1     exam2
Andre   0.707107 -0.707107
Barry   0.707107 -0.707107
Chris   0.707107 -0.707107
Dan     0.707107 -0.707107
Emilio  0.707107 -0.707107

In [167]:
import matplotlib.pyplot as plt
import seaborn as sns

values = np.array([1, 3, 2, 4, 1, 6, 4])
example_df = pd.DataFrame({
    'value': values,
    'even': values % 2 == 0,
    'above_three': values > 3 
}, index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])

# Examine DataFrame
print example_df

  above_three   even  value
a       False  False      1
b       False  False      3
c       False   True      2
d        True   True      4
e       False  False      1
f        True   True      6
g        True   True      4


In [169]:
# Examine groups

grouped_data = example_df.groupby('even')
# The groups attribute is a dictionary mapping keys to lists of row indexes
grouped_data.groups

{False: Index([u'a', u'b', u'e'], dtype='object'),
 True: Index([u'c', u'd', u'f', u'g'], dtype='object')}

In [171]:
# Group by multiple columns
grouped_data = example_df.groupby(['even', 'above_three'])
grouped_data.groups

{(False, False): Index([u'a', u'b', u'e'], dtype='object'),
 (True, False): Index([u'c'], dtype='object'),
 (True, True): Index([u'd', u'f', u'g'], dtype='object')}

In [172]:
# Get sum of each group

grouped_data = example_df.groupby('even')
grouped_data.sum()

above_three  value
even                     
False          0.0      5
True           3.0     16

In [173]:
# Limit columns in result

grouped_data = example_df.groupby('even')

# You can take one or more columns from the result DataFrame
print grouped_data.sum()['value']

print '\n' # Blank line to separate results

# You can also take a subset of columns from the grouped data before 
# collapsing to a DataFrame. In this case, the result is the same.
print grouped_data['value'].sum()

even
False     5
True     16
Name: value, dtype: int64


even
False     5
True     16
Name: value, dtype: int64


In [174]:
filename = '../ch3_data/nyc_subway_weather.csv'
subway_df = pd.read_csv(filename)

subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0            0.0  2011-05-01 00:00:00     0         6     ...           30.22   
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5         0.0         30.258      55.98       7.86   
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [175]:
subway_df.groupby('day_week')

In [176]:
subway_df.groupby('day_week').mean()

ENTRIESn        EXITSn  ENTRIESn_hourly  EXITSn_hourly  \
day_week                                                               
0         2.840276e+07  2.006446e+07      1825.264907    1304.046505   
1         2.846201e+07  2.013426e+07      2164.836433    1537.704955   
2         2.759311e+07  1.954360e+07      2297.097957    1637.824152   
3         2.774932e+07  1.959388e+07      2317.072379    1638.763537   
4         2.798019e+07  1.972139e+07      2277.372294    1621.136514   
5         2.809505e+07  1.984991e+07      1383.901479    1052.769316   
6         2.836150e+07  2.001703e+07      1066.436106     826.832324   

               hour  weekday   latitude  longitude       fog   precipi  \
day_week                                                                 
0         10.012553      1.0  40.724701 -73.940259  0.000000  0.000595   
1          9.959392      1.0  40.724725 -73.940213  0.006673  0.014065   
2         10.059103      1.0  40.724626 -73.940252  0.038672  0.010773   
3         10.056518      1.0  40.724578 -73.940469  0.004376  0.001696   
4         10.052110      1.0  40.724469 -73.940258  0.000000  0.000857   
5         10.107209      0.0  40.724769 -73.940675  0.000000  0.000000   
6         10.102526      0.0  40.724631 -73.940473  0.020092  0.003055   

          pressurei      rain      tempi     wspdi  meanprecipi  \
day_week                                                          
0         29.993017  0.212268  62.584665  7.934180     0.000595   
1         29.978990  0.201193  65.760642  8.365128     0.014065   
2         29.973333  0.499818  61.456348  7.767858     0.010773   
3         29.976963  0.163537  62.110100  7.552944     0.001696   
4         29.945215  0.249174  62.636899  4.773413     0.000857   
5         29.912752  0.061368  64.529593  5.297283     0.000000   
6         30.001086  0.199882  62.252711  6.241380     0.003055   

          meanpressurei  meantempi  meanwspdi  weather_lat  weather_lon  
day_week                                                                 
0             29.993017  62.584665   7.934180    40.728668   -73.938591  
1             29.978990  65.760642   8.365128    40.728664   -73.938464  
2             29.973333  61.456348   7.767858    40.728592   -73.938707  
3             29.976963  62.110100   7.552944    40.728496   -73.938749  
4             29.945215  62.636899   4.773413    40.728321   -73.938448  
5             29.912752  64.529593   5.297283    40.728610   -73.939098  
6             30.001086  62.252711   6.241380    40.728488   -73.938856

In [178]:
ridership_by_day = subway_df.groupby('day_week').mean()['ENTRIESn_hourly']
print ridership_by_day

day_week
0    1825.264907
1    2164.836433
2    2297.097957
3    2317.072379
4    2277.372294
5    1383.901479
6    1066.436106
Name: ENTRIESn_hourly, dtype: float64
